global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # LwM2M Server metrics
  - job_name: 'lwm2m-server'
    static_configs:
      - targets: ['lwm2m-server:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Sparkplug B Host Application metrics
  - job_name: 'sparkplug-host'
    static_configs:
      - targets: ['sparkplug-host:8081']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # MQTT Monitor metrics
  - job_name: 'mqtt-monitor'
    static_configs:
      - targets: ['mqtt-monitor:8082']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # MQTT to Redpanda Bridge metrics
  - job_name: 'mqtt-redpanda-bridge'
    static_configs:
      - targets: ['mqtt-redpanda-bridge:8083']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Redpanda metrics
  - job_name: 'redpanda'
    static_configs:
      - targets: ['redpanda:9644']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # NOTE: Removed non-existent services:
  # - cadvisor: Not deployed in our setup
  # - node-exporter: Not deployed in our setup  
  # - mqtt-broker: Mosquitto doesn't expose metrics on port 9091 