# Simulator FDI Configuration
# Minimal setup for testing FDI workflow with device simulators
# This configuration can be reused for any device simulator

version: '3.8'

services:
  # Device Simulator (Smart Breaker)
  device-simulator:
    build: 
      context: ../../device-simulators
      dockerfile: Dockerfile
    container_name: device-simulator
    restart: unless-stopped
    environment:
      # Device Identity
      - DEVICE_ID=smart-breaker-001
      - DEVICE_TYPE=SmartBreaker
      - DEVICE_MANUFACTURER=Smart
      - DEVICE_MODEL=XSeries-SmartBreaker-TypeB
      - DEVICE_SERIAL_NUMBER=ETN-XSB-001
      - DEVICE_FIRMWARE_VERSION=2.1.0
      
      # Electrical Ratings
      - RATED_CURRENT=100.0
      - RATED_VOLTAGE=480.0
      - RATED_FREQUENCY=60.0
      - BREAKING_CAPACITY=25.0
      - POLE_COUNT=3
      - MOUNTING_TYPE=PanelMount
      - PROTECTION_CLASS=TypeB
      
      # Protection Settings
      - OVERCURRENT_PICKUP=100.0
      - OVERCURRENT_DELAY=1000.0
      - GROUND_FAULT_PICKUP=5.0
      - GROUND_FAULT_DELAY=500.0
      - ARC_FAULT_PICKUP=50.0
      - ARC_FAULT_DELAY=100.0
      - THERMAL_PICKUP=120.0
      - THERMAL_DELAY=300.0
      
      # Communication Settings (Local API mode)
      - MQTT_BROKER_HOST=localhost
      - MQTT_BROKER_PORT=1883
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
      - MQTT_USE_TLS=false
      
      # LwM2M Server Settings
      - LWM2M_SERVER_HOST=localhost
      - LWM2M_SERVER_PORT=8080
      
      # Sparkplug B Settings
      - GROUP_ID=IIoT
      - SPARKPLUG_NAMESPACE=spBv1.0
      
      # Performance Settings
      - TELEMETRY_INTERVAL=1.0
      - LWM2M_INTERVAL=5.0
      
      # Protection Monitoring
      - PROTECTION_MONITORING_INTERVAL=1.0
      - MAINTENANCE_MONITORING_INTERVAL=60
      
      # Maintenance Thresholds
      - MAINTENANCE_OPERATING_HOURS=5000
      - MAINTENANCE_TRIP_COUNT=1000
      - MAINTENANCE_TEMPERATURE_THRESHOLD=75.0
      
      # Auto-reclose Settings
      - AUTO_RECLOSE_ENABLED=false
      - AUTO_RECLOSE_ATTEMPTS=1
      - AUTO_RECLOSE_DELAY=5.0
      
      # Security Settings
      - SECURITY_LEVEL=Standard
      - REMOTE_CONTROL_ENABLED=true
      
      # Logging Configuration
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
    volumes:
      - ../../fdi/device-profiles:/app/device-profiles:ro
      - ../../device-simulators/simulators/smart_breaker_simulator.py:/app/smart_breaker_simulator.py
    command: ["python", "smart_breaker_simulator.py"]
    networks:
      - simulator-network
    ports:
      - "8080:8080"  # Device API port
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  # FDI Server with Plugin Architecture
  fdi-server:
    build:
      context: ../../fdi/fdi-device-driver
      dockerfile: Dockerfile
    container_name: fdi-server
    restart: unless-stopped
    environment:
      # FDI Server Configuration
      - FDI_PACKAGE_PATH=/app/device-profiles/smart-breaker.fdi
      - FDI_ADAPTER=local_api
      - DEVICE_MODULE=smart_breaker_simulator
      
      # Logging
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
    volumes:
      - ../../fdi/device-profiles:/app/device-profiles:ro
      - ../../fdi/fdi-device-driver:/app/fdi-driver:ro
      - ../../device-simulators:/app/device-simulators:ro
    working_dir: /app
    command: ["python", "fdi_server.py"]
    networks:
      - simulator-network
    ports:
      - "8081:8081"  # FDI Server API port
    depends_on:
      - device-simulator
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  # FDI Web Demo (Optional)
  fdi-web-demo:
    build:
      context: ../../fdi/demos
      dockerfile: Dockerfile
    container_name: fdi-web-demo
    restart: unless-stopped
    environment:
      - FDI_SERVER_URL=http://fdi-server:8081
      - DEVICE_PROFILE_PATH=/app/device-profiles/smart-breaker.fdi
    volumes:
      - ../../fdi/device-profiles:/app/device-profiles:ro
      - ../../fdi/templates:/app/templates:ro
      - ../../fdi/demos:/app/demos:ro
    working_dir: /app
    command: ["python", "fdi_web_demo.py"]
    networks:
      - simulator-network
    ports:
      - "8082:8082"  # Web Demo port
    depends_on:
      - fdi-server
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
        reservations:
          memory: 64M
          cpus: '0.05'

networks:
  simulator-network:
    driver: bridge 