# NOTE: Monitoring services (Prometheus, Grafana, MQTT Monitor) are COMMENTED OUT
# to prevent disk space issues. These services can accumulate large amounts of data.
# To enable monitoring, uncomment the services below and ensure sufficient disk space.

services:
  # MQTT Broker - Edge message hub for device interoperability
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: lwm2m-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"     # Plain MQTT (edge devices)
      - "8883:8883"     # MQTT over TLS (edge devices)
      - "9001:9001"     # WebSocket (edge devices)
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/passwd:/mosquitto/config/passwd
      - ./certs:/mosquitto/certs
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - iot-network

  # Redpanda - Cloud event streaming platform (LwM2M only)
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: iot-redpanda
    restart: unless-stopped
    ports:
      - "8084:8081"     # HTTP API (Schema Registry)
      - "8085:8082"     # Admin API (PandaProxy)
      - "9092:9092"     # Kafka API
      - "9644:9644"     # Metrics
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
      - --schema-registry-addr 0.0.0.0:8081
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    networks:
      - iot-network

  # Redpanda Console - Web UI for Redpanda management
  redpanda-console:
    image: redpandadata/console:latest
    container_name: iot-redpanda-console
    restart: unless-stopped
    ports:
      - "8086:8080"     # Web UI
    environment:
      - REDPANDA_BROKERS=redpanda:29092
      - REDPANDA_SCHEMA_REGISTRY_URL=http://redpanda:8081
      - KAFKA_BROKERS=redpanda:29092
    depends_on:
      - redpanda
    networks:
      - iot-network

  # Redpanda Connect - HTTP to Kafka Bridge (LwM2M events only)
  redpanda-connect:
    image: redpandadata/connect:latest
    container_name: iot-redpanda-connect
    restart: unless-stopped
    ports:
      - "8087:4195"     # Connect HTTP API
    volumes:
      - ./redpanda-connect-config.yaml:/connect.yaml
    depends_on:
      - redpanda
      - lwm2m-server
    networks:
      - iot-network

  # LwM2M Server - Cloud device management and event streaming
  lwm2m-server:
    build: ./lwm2m-server
    container_name: lwm2m-server
    restart: unless-stopped
    ports:
      - "8080:8080"     # Web UI & HTTP API
      - "5684:5684/udp" # CoAP (backup transport)
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=8883
      - MQTT_USE_TLS=true
      - SERVER_PORT=8080
    volumes:
      - ./certs:/app/certs:ro
      - lwm2m_data:/app/data
      - ./lwm2m-server/server.py:/app/server.py
    depends_on:
      - mosquitto
    networks:
      - iot-network

  # Device Simulator - Edge devices with LwM2M (cloud) + Sparkplug B (edge)
  device-simulator:
    build: ./device-simulator
    restart: unless-stopped
    environment:
      - DEVICE_COUNT=7
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
      - MQTT_USE_TLS=false
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
      - LWM2M_SERVER_HOST=lwm2m-server
      - LWM2M_SERVER_PORT=8080
      - GROUP_ID=IIoT
      - SPARKPLUG_NAMESPACE=spBv1.0
      # NOTE: TELEMETRY_INTERVAL and LWM2M_INTERVAL are HARDCODED in Python code
    volumes:
      - ./certs:/app/certs:ro
      - ./device-profiles:/app/device-profiles:ro
    depends_on:
      - mosquitto
      - lwm2m-server
    networks:
      - iot-network
    deploy:
      replicas: 1

  # Prometheus - Metrics collection (COMMENTED OUT TO SAVE SPACE)
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: lwm2m-prometheus
  #   restart: unless-stopped
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #     - prometheus_data:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/etc/prometheus/console_libraries'
  #     - '--web.console.templates=/etc/prometheus/consoles'
  #     - '--storage.tsdb.retention.time=200h'
  #     - '--web.enable-lifecycle'
  #   networks:
  #     - iot-network

  # Grafana - Metrics visualization (COMMENTED OUT TO SAVE SPACE)
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: lwm2m-grafana
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #     - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
  #   volumes:
  #     - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
  #     - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
  #     - grafana_data:/var/lib/grafana
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - iot-network

  # MQTT Message Monitor - Edge device interoperability monitoring (COMMENTED OUT TO SAVE SPACE)
  # mqtt-monitor:
  #   build: ./mqtt-monitor
  #   container_name: mqtt-monitor
  #   restart: unless-stopped
  #   ports:
  #     - "8082:8082"     # Web interface
  #   environment:
  #     - MQTT_BROKER_HOST=mosquitto
  #     - MQTT_BROKER_PORT=8883
  #     - MQTT_USE_TLS=true
  #     - WEB_PORT=8082
  #   volumes:
  #     - ./certs:/app/certs:ro
  #   depends_on:
  #     - mosquitto
  #   networks:
  #     - iot-network

volumes:
  mosquitto_data:
  mosquitto_log:
  lwm2m_data:
  # prometheus_data:  # COMMENTED OUT TO SAVE SPACE
  # grafana_data:     # COMMENTED OUT TO SAVE SPACE
  redpanda_data:

networks:
  iot-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 